More UI and better installer

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,18 +1,30 @@
 #!/bin/bash
 function installgit() {
 	mv ~/.ssh/authorized_keys ~/authorized_keys.custom 2>/dev/null
-	mkdir ~/.ssh 2>/dev/null
-	mkdir ~/var ~/var/tmp ~/var/locks || exit 1
+	touch ~/authorized_keys.custom
+	mkdir -p ~/.ssh
+	mkdir -p ~/var ~/var/tmp ~/var/locks ~/repos || exit 1
 	cp -a gitjoin/ webapp/ *.py ~ || exit 1
-	touch ~/config.py || exit 1
+	bash genconf.sh > ~/config.py
 	echo Ok. Now edit $HOME/config.py
 }
 
 if [ "$(whoami)" = root ]; then
-	useradd git
-	mkdir ~git 2>/dev/null
-	chown git ~git || exit
-	su git -c "bash $0"
+	printf "Enter name of user to create (empty to abort): "
+	read username
+	if [ "$username" = "" ]; then
+		echo Abort.
+		exit 1
+	fi
+	useradd $username
+	home=`su $username -c 'echo ~'`
+	if [ "$home" = "" ]; then
+		echo Failed to get home directory of $username.
+		exit 1
+	fi
+	mkdir -p $home || exit
+	chown $username $home || exit
+	su $username -c "bash $0"
 else
 	printf "Overwrite %s? (uppercase yes/no): " "$HOME"
 	read yesorno
